server:
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    dirverClassName: com.mysql.jdbc.Diver
    url: jdbc:mysql://localhost:3306/httt_quan_ly
    username: root
    password: cuong#Super2001